"use client";

import { motion } from "framer-motion";
import ScrollReveal from "@/components/ScrollReveal";

const EXPERIENCES = [
  {
    org: "Kuan Lab, Yale School of Medicine",
    period: "Jan 2026 - Present",
    location: "New Haven, CT",
    description: [
      "Data systems and analytics pipeline work for large-scale 3D medical imaging, built around post-segmentation analysis needs in the Kuan Lab.",
      "Designed modular ingestion, chunked HDF5/Zarr-style storage, graph construction, conservative validation checks, and diagnostics for inspecting accepted versus rejected connections.",
      "Collaborated with lab stakeholders to keep the pipeline useful for downstream analysis and visualization rather than just technically complete.",
    ],
  },
  {
    org: "Spintronic Quantum Material Laboratory",
    period: "May - Aug 2025",
    location: "Hong Kong",
    description: [
      "AI hardware-software research on a next-generation MTJ-based in-memory accelerator, translating device and system constraints into software requirements.",
      "Built validation pipelines benchmarking power, latency, throughput, and bottlenecks so the hardware team could reason about feasible use cases and performance guarantees.",
    ],
  },
  {
    org: "Yale Intelligent Computing Lab",
    period: "Sept 2024 - Sept 2025",
    location: "New Haven, CT",
    description: [
      "Developed reproducible deployment pipelines for transformer models on Raspberry Pi and embedded Linux platforms.",
      "Created Python profiling frameworks and dashboards to compare latency, memory footprint, power draw, and accuracy across pruning, quantization, and model-design choices.",
    ],
  },
  {
    org: "Martin Andraud Group, UCLouvain",
    period: "May - Sept 2024",
    location: "Louvain-la-Neuve, Belgium",
    description: [
      "Software-hardware co-design work on a 22nm mixed-signal Compute-In-Memory accelerator, bridging RISC-V control firmware with circuit-level behavior.",
      "Integrated calibration and control routines that improved compute reliability by 25-45% across operating conditions and translated results for hardware, firmware, and algorithm collaborators.",
    ],
  },
  {
    org: "FutureTEC",
    period: "Jul - Aug 2023",
    location: "Amman, Jordan",
    description: [
      "Security operations internship with a cyber defense team, using SIEM tools to analyze live alerts generated by applications and network hardware.",
      "Supported incident-response recommendations, log correlation, and cross-cultural technical communication in Arabic.",
    ],
  },
];

const PROJECTS = [
  {
    title: "Automated Composting System",
    description: [
      "Led hardware-software product design for a smart composter prototype intended for Yale's fourteen residential dining halls.",
      "Developed microcontroller software for temperature, humidity, and CO2 sensor readings, modular drivers, and closed-loop actuator control to stabilize the composting environment in real time.",
    ],
  },
  {
    title: "Real-Time ResNet18 on Raspberry Pi",
    description: [
      "Pruned and quantized ResNet18 for real-time computer vision inference on a Raspberry Pi.",
      "Built evaluation tools and roofline analyses to identify compute-bound versus memory-bound layers and tune power, latency, and user-experience tradeoffs on constrained hardware.",
    ],
  },
  {
    title: "GPT-Lite FPGA Optimization",
    description: [
      "Took NanoGPT and mapped it onto FPGA fabric, a fundamentally different compute paradigm than the GPU training pipelines the model was designed for.",
      "Designed a software-driven optimization workflow with model refactoring, quantization, and profiling that reduced compute and memory footprint while preserving 99% of baseline accuracy.",
    ],
  },
];

const YCC_INITIATIVES = [
  "Led student-administration working sessions on campus technology, privacy, and access issues.",
  "Authored decision memos and briefing materials for non-technical stakeholders evaluating policy, governance, and rollout tradeoffs.",
  "Advanced Clarity AI platform adoption and Anthropic Claude credit access for Yale labs.",
  "Opened Yale CAS pathways to student developers and built an industry partnership channel through student government.",
];

const DIPLOMATIC = [
  {
    title: "U.S. State Department NSLI-Y Scholar",
    detail:
      "Taiwan, Dec 2021 - May 2022. One of 13 scholars selected for a funded Mandarin and cultural study fellowship at Wenzao Ursuline University; conducted Mandarin-language youth surveys on Taiwanese cultural and political identity.",
  },
  {
    title: "Congress-Bundestag Youth Exchange Scholar",
    detail:
      "Germany, Aug 2021 - Dec 2021. Selected for the U.S.-German bilateral fellowship with study, government-sponsored training, diplomatic activity, and research on innovation policy and European technology ecosystems.",
  },
  {
    title: "U.S. Consulate Hamburg Youth Council",
    detail:
      "Germany, Jan 2022 - May 2022. American council member in Consul General Darion Akins's youth council, working with American and German scholars during the early months of the Ukraine crisis.",
  },
  {
    title: "U.S. Youth Ambassador",
    detail:
      "Argentina & Chile, Jun 2020 - Jun 2021. One of 48 students nationwide selected by the State Department's Bureau of Educational and Cultural Affairs; led community projects and later served as an Alumni Ambassador for program outreach.",
  },
  {
    title: "Congressional Advisory Council Leader",
    detail:
      "NJ-7th District, Nov 2019 - Jul 2022. Led a 12-member youth policy team on energy, foreign affairs, and technology recommendations presented directly to Rep. Tom Malinowski.",
  },
];

const AWARDS = [
  {
    title: "Yale STARS Science Fellowship",
    detail: "Science, Technology and Research Scholars Program.",
  },
  {
    title: "Congressional Commendation",
    detail: "U.S. House of Representatives. National.",
  },
  {
    title: "U.S. State Department Fellow",
    detail: "NSLI-Y, CBYX, and Youth Ambassadors programs.",
  },
  {
    title: "Kennedy-Lugar Youth Scholarship Finalist",
    detail: "National.",
  },
  {
    title: "Alan S. Tetelman 1958 Fellowship",
    detail: "International research in the sciences.",
  },
  {
    title: "ISA Award for Advanced Arabic Study",
    detail: "Amman, Jordan.",
  },
];

export default function Home() {
  return (
    <>
      {/* Hero */}
      <section className="min-h-screen flex items-center page-section pt-20">
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.6, delay: 0.1 }}
        >
          <h1 className="font-display text-[clamp(3rem,10vw,8rem)] leading-[0.9] tracking-tight mb-6">
            Joseph
            <br />
            Elsayyid
          </h1>

          <p className="max-w-md text-base text-text-secondary font-body leading-relaxed mb-10">
            Yale-trained engineer and technology leader focused on how advanced
            computing moves from labs into public institutions. My work spans
            research, campus technology leadership, and cross-cultural diplomacy
            across East Asia, Europe, and the Middle East.
          </p>

          <div className="flex flex-wrap gap-x-5 gap-y-2 font-mono text-xs text-text-muted tracking-wider">
            <a
              href="mailto:elsayyidjoseph@gmail.com"
              className="hover:text-text-secondary transition-colors duration-300"
            >
              elsayyidjoseph@gmail.com
            </a>
            <a
              href="/resume.pdf"
              target="_blank"
              rel="noopener noreferrer"
              className="hover:text-text-secondary transition-colors duration-300"
            >
              Resume
            </a>
          </div>
        </motion.div>
      </section>

      {/* Work */}
      <section id="work" className="py-24 md:py-32 page-section">
        <div className="max-w-2xl">
          <ScrollReveal>
            <h2 className="font-display text-[clamp(2rem,5vw,4rem)] leading-[0.95] tracking-tight mb-16">
              Work
            </h2>
          </ScrollReveal>

          {EXPERIENCES.map((exp, i) => (
            <ScrollReveal key={i} delay={i * 0.05}>
              <div
                className={`py-8 ${
                  i < EXPERIENCES.length - 1 ? "border-b border-border" : ""
                }`}
              >
                <div className="flex flex-col md:flex-row md:items-baseline md:justify-between gap-1 mb-1">
                  <h3 className="font-display text-xl text-text-primary">
                    {exp.org}
                  </h3>
                  <span className="font-mono text-xs text-text-muted tracking-wider shrink-0">
                    {exp.period}
                  </span>
                </div>
                <p className="font-mono text-xs text-text-muted tracking-wider mb-3">
                  {exp.location}
                </p>
                {exp.description.map((para, j) => (
                  <p
                    key={j}
                    className="font-body text-sm text-text-secondary leading-relaxed mb-2 last:mb-0"
                  >
                    {para}
                  </p>
                ))}
              </div>
            </ScrollReveal>
          ))}
        </div>
      </section>

      {/* Projects */}
      <section id="projects" className="py-24 md:py-32 border-t border-border page-section">
        <div className="max-w-2xl">
          <ScrollReveal>
            <h2 className="font-display text-[clamp(2rem,5vw,4rem)] leading-[0.95] tracking-tight mb-16">
              Projects
            </h2>
          </ScrollReveal>

          {PROJECTS.map((project, i) => (
            <ScrollReveal key={i} delay={i * 0.05}>
              <div
                className={`py-8 ${
                  i < PROJECTS.length - 1 ? "border-b border-border" : ""
                }`}
              >
                <h3 className="font-display text-xl text-text-primary mb-3">
                  {project.title}
                </h3>
                {project.description.map((para, j) => (
                  <p
                    key={j}
                    className="font-body text-sm text-text-secondary leading-relaxed mb-2 last:mb-0"
                  >
                    {para}
                  </p>
                ))}
              </div>
            </ScrollReveal>
          ))}
        </div>
      </section>

      {/* Leadership */}
      <section id="leadership" className="py-24 md:py-32 border-t border-border page-section">
        <div className="max-w-2xl">
          <ScrollReveal>
            <h2 className="font-display text-[clamp(2rem,5vw,4rem)] leading-[0.95] tracking-tight mb-16">
              Leadership
            </h2>
          </ScrollReveal>

          <ScrollReveal>
            <div className="mb-12">
              <h3 className="font-display text-xl text-text-primary mb-4">
                YCC Tech Division Chair
              </h3>
              <ul className="space-y-2">
                {YCC_INITIATIVES.map((item, i) => (
                  <li
                    key={i}
                    className="font-body text-sm text-text-secondary leading-relaxed"
                  >
                    {item}
                  </li>
                ))}
              </ul>
            </div>
          </ScrollReveal>

          <ScrollReveal delay={0.05}>
            <div className="mb-12 pb-12 border-b border-border">
              <h3 className="font-display text-xl text-text-primary mb-2">
                Student Advisory, Yale College
              </h3>
              <p className="font-body text-sm text-text-secondary leading-relaxed">
                Competitively selected to advise Yale College on Science &
                Quantitative Reasoning resource allocation priorities under
                Dean Alexia Belperron.
              </p>
            </div>
          </ScrollReveal>

          <ScrollReveal delay={0.1}>
            <div>
              <span className="font-mono text-xs text-text-muted tracking-[0.2em] uppercase block mb-8">
                Government & Diplomatic
              </span>
              {DIPLOMATIC.map((exp, i) => (
                <div
                  key={i}
                  className={`py-6 ${
                    i < DIPLOMATIC.length - 1 ? "border-b border-border" : ""
                  }`}
                >
                  <h3 className="font-display text-lg text-text-primary mb-1">
                    {exp.title}
                  </h3>
                  <p className="font-body text-sm text-text-secondary">
                    {exp.detail}
                  </p>
                </div>
              ))}
            </div>
          </ScrollReveal>
        </div>
      </section>

      {/* About */}
      <section id="about" className="py-24 md:py-32 border-t border-border page-section">
        <div className="max-w-2xl">
          <ScrollReveal>
            <h2 className="font-display text-[clamp(2rem,5vw,4rem)] leading-[0.95] tracking-tight mb-16">
              About
            </h2>
          </ScrollReveal>

          <div className="space-y-6 mb-16">
            <ScrollReveal>
              <p className="font-body text-base text-text-secondary leading-relaxed">
                I&rsquo;m an engineer with a B.S. in Electrical Engineering &
                Computer Science from Yale, now pursuing the M.M.S. in
                Technology Management at Yale SOM. My work has ranged from
                22-nanometer compute-in-memory accelerators in Belgium to AI
                hardware in Hong Kong to medical imaging data systems at Yale
                School of Medicine.
              </p>
            </ScrollReveal>
            <ScrollReveal delay={0.05}>
              <p className="font-body text-base text-text-secondary leading-relaxed">
                Before Yale, I was a U.S. State Department fellow in Taiwan, a
                Congress-Bundestag scholar in Germany, and a youth ambassador in
                Argentina and Chile. I work across Mandarin, Arabic, and Spanish
                at a professional level, with working French and German.
              </p>
            </ScrollReveal>
          </div>

          <ScrollReveal delay={0.15}>
            <div className="border-t border-border pt-8 space-y-6">
              <div>
                <span className="font-mono text-xs text-text-muted tracking-[0.2em] uppercase block mb-3">
                  Education
                </span>
                <p className="font-body text-sm text-text-primary">
                  Yale School of Management
                </p>
                <p className="font-body text-sm text-text-secondary mb-3">
                  M.M.S. Technology Management, 2026-27
                </p>
                <p className="font-body text-sm text-text-primary">
                  Yale University
                </p>
                <p className="font-body text-sm text-text-secondary mb-3">
                  B.S. Electrical Engineering & Computer Science, completed 2026
                </p>
                <p className="font-body text-sm text-text-primary">
                  Wenzao Ursuline University of Languages
                </p>
                <p className="font-body text-sm text-text-secondary">
                  Chinese Studies, 2021-22
                </p>
              </div>

              <div>
                <span className="font-mono text-xs text-text-muted tracking-[0.2em] uppercase block mb-3">
                  Honors & Awards
                </span>
                <div className="space-y-2">
                  {AWARDS.map((award, i) => (
                    <div key={i}>
                      <p className="font-body text-sm text-text-primary">
                        {award.title}
                      </p>
                      <p className="font-body text-sm text-text-secondary">
                        {award.detail}
                      </p>
                    </div>
                  ))}
                </div>
              </div>

              <div>
                <span className="font-mono text-xs text-text-muted tracking-[0.2em] uppercase block mb-3">
                  Contact
                </span>
                <div className="space-y-1">
                  <a
                    href="mailto:elsayyidjoseph@gmail.com"
                    className="block font-body text-sm text-text-primary hover:text-accent transition-colors duration-300"
                  >
                    elsayyidjoseph@gmail.com
                  </a>
                  <a
                    href="/resume.pdf"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="block font-body text-sm text-text-primary hover:text-accent transition-colors duration-300"
                  >
                    Resume (PDF)
                  </a>
                  <p className="font-body text-sm text-text-secondary">
                    New Haven, CT
                  </p>
                </div>
              </div>
            </div>
          </ScrollReveal>
        </div>
      </section>
    </>
  );
}
